### ISSUE TITLE
Nuget Package Installation Error

### ISSUE THREAD

**Issue by karembou** [kloarubeek/SendyClient.Net#10]
Hi, 

Not sure where to start but 

I was trying to install the SendyClient.Net 3.0.0 using nuget package but keep getting the error that "the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author." 

If any insight of what I should be looking at to get this working would be great.

Also the SendyCampaignsAPI.zip link is dead was wondering if you have a copy would be great.

Thanks in adavnce

Regards,
Karembeu

**Comment by kloarubeek** [comment]
Hi Karembeu, which .Net Core version do you use?

**Comment by kloarubeek** [comment]
About the zip file: I don't know which zip file you mean? There is nu such zip file in this repo.

**Comment by karembou** [comment]
Thanks for your response, it shows a 4.7.2 installed. The error I get is 

"Could not install package 'SendyClient.Net 3.0.0'. You are trying to install this package into a project that targets '.NETFramework,Version=v4.7.2', but the package does not contain any assembly references or content files that are compatible with that framework. For more information, contact the package author"

My apologies for not being clear on the second question. The zip file would be the Campaign API link found in the Readme.me file, in the 'How to use' section.

Thanks in advance

Regards,
Karembeu

**Comment by kloarubeek** [comment]
I use it on a 4.6.1 project and in a .Net Core 2.1 project. I'll update to 4.7.2 to see what happens.

The zip is maintained by someone else who provided it via de Sendy forum. Please submit a question on his forum post https://sendy.co/forum/discussion/768/added-some-api-functionality/p1.

**Comment by kloarubeek** [comment]
I tested it both on 4.6.1 and 4.7, both were successful. Could you try the suggestions from Stackoverflow: https://stackoverflow.com/questions/34991703/nuget-package-installation-failure ?

**Comment by karembou** [comment]
Apparently the forum hasn't been active for a while and thought I would ask you. Sorry to bother you again about this but there is another question about custom fields. I have been trying to import html code using the custom field import in sendy's app but every time it strips the html code. For example I tried uploading in the custom fields (text) '12345 < b r > 12345' and the < b r > gets stripped or removed. My main target is trying to add a carriage return in between the two numbers. 
Any idea on how to get this working?

**Comment by kloarubeek** [comment]
Actually I don't know. But you can easily check how Sendy handles this: it's php so you can read the scripts how they process or filter your html code.

**Comment by kloarubeek** [comment]
Did you manage to use this nuget package in your application?

**Comment by karembou** [comment]
Yes, apologies for not closing the issue and you are right, I would for sure find my answer in the php code. Thanks again for your help :)
