### ISSUE TITLE
Updated API support

### ISSUE THREAD

**Issue by mguinness** [kloarubeek/SendyClient.Net#8]
Thanks for the great library, I've just started using it and it works great so far.  One minor quibble is that it would be nice to suffix the method names with Async (or alternatively the class name) as is convention.

One issue I've come across is that the library doesn't support the newer features of the [Create Campaign](https://sendy.co/api#5) API as it's missing the segment_ids, exclude_list_ids & exclude_segments_ids parameters.  Also the [Subscribe](https://sendy.co/api#0) API is missing country, ipaddress, referrer & gdpr parameters.

I'd be happy to try a PR if that's something you don't have time for, but I wanted to get your input first.  I think SendyClient would also need a version number to determine support.

**Comment by kloarubeek** [comment]
You're right about the suffix and the missing features. I created the client before that and didn't update it for version 3. If you can create a pull request, I'm happy to review and merge it!

Don't fotget to increase the major version number as it will break the contract with the Async suffix :smile:
